# Security & Performance
# Higher iterations = more secure but slower to start sync
iterations = 600000

# Use mtime/size check by default for instant incremental syncs
fast = true

# Keychain Defaults
keychain-service = vaultcrypt
keychain-account = anakin

# Global Exclusions
exclude = .DS_Store
exclude = .localized
exclude = .git/
exclude = node_modules/
exclude = vendor/
exclude = *.tmp
exclude = .*.swp
exclude = .DS_Store
exclude = .venv/
exclude = venv/
exclude = .env/
exclude = env/
